# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  view:
    view_response_listener: true
    formats: { json: true, xml: false, rss: false }

    mime_types:
      json: ['application/json']

  format_listener:
    rules:
      - { path: '^/api/', fallback_format: json, priorities: [json] }
